2015-07-21 12:01:09,338 dd272e43 MainThread pkb.py:336 INFO     Flag values:
--machine_type=ExtraSmall
--cloud=Azure
--benchmarks=iperf
2015-07-21 12:01:09,456 dd272e43 MainThread publisher.py:501 DEBUG    Using publishers: [<LogPublisher logger=<logging.RootLogger object at 0x7fa5cfb1e990> level=20>, <PrettyPrintStreamPublisher stream=<open file '<stdout>', mode 'w' at 0x7fa5d161d150>>, <NewlineDelimitedJSONPublisher file_path="/tmp/perfkitbenchmarker/run_dd272e43/perfkitbenchmarker_results.json" mode="wb">]
2015-07-21 12:01:09,457 dd272e43 MainThread iperf(1/1) pkb.py:194 INFO     Preparing benchmark iperf
2015-07-21 12:01:09,460 dd272e43 Thread-1 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:09,460 dd272e43 Thread-1 iperf(1/1) vm_util.py:392 INFO     Running: azure account affinity-group create --location=East US --label=perfkitdd272e434581a4b1f perfkitdd272e434581a4b1f
2015-07-21 12:01:11,111 dd272e43 Thread-1 iperf(1/1) vm_util.py:418 INFO     Ran azure account affinity-group create --location=East US --label=perfkitdd272e434581a4b1f perfkitdd272e434581a4b1f. Got return code (1).
STDOUT: info:    Executing command account affinity-group create
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   There is no current subscription. Please use the azure login command to set your current subscription.
error:   account affinity-group create command failed


2015-07-21 12:01:11,111 dd272e43 Thread-1 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:11,112 dd272e43 Thread-1 iperf(1/1) vm_util.py:392 INFO     Running: azure account affinity-group show --json perfkitdd272e434581a4b1f
2015-07-21 12:01:12,514 dd272e43 Thread-1 iperf(1/1) vm_util.py:420 DEBUG    Ran azure account affinity-group show --json perfkitdd272e434581a4b1f. Got return code (1).
STDOUT: 
STDERR: There is no current subscription. Please use the azure login command to set your current subscription.
Error information has been recorded to /root/.azure/azure.err
account affinity-group show command failed


2015-07-21 12:01:12,515 dd272e43 Thread-1 iperf(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureAffinityGroup failed.
2015-07-21 12:01:22,868 dd272e43 Thread-4 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:22,868 dd272e43 Thread-4 iperf(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-dd272e43-1
2015-07-21 12:01:22,870 dd272e43 Thread-5 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:22,870 dd272e43 Thread-5 iperf(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-dd272e43-0
2015-07-21 12:01:24,556 dd272e43 Thread-5 iperf(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-dd272e43-0. Got return code (1).
STDOUT: info:    Executing command vm delete
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   There is no current subscription. Please use the azure login command to set your current subscription.
error:   vm delete command failed


2015-07-21 12:01:24,556 dd272e43 Thread-5 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:24,556 dd272e43 Thread-5 iperf(1/1) vm_util.py:392 INFO     Running: azure vm show --json pkb-dd272e43-0
2015-07-21 12:01:24,588 dd272e43 Thread-4 iperf(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-dd272e43-1. Got return code (1).
STDOUT: info:    Executing command vm delete
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   There is no current subscription. Please use the azure login command to set your current subscription.
error:   vm delete command failed


2015-07-21 12:01:24,588 dd272e43 Thread-4 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:24,588 dd272e43 Thread-4 iperf(1/1) vm_util.py:392 INFO     Running: azure vm show --json pkb-dd272e43-1
2015-07-21 12:01:25,578 dd272e43 MainThread iperf(1/1) pkb.py:426 INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/run_dd272e43/pkb.log
2015-07-21 12:01:25,589 dd272e43 Thread-4 iperf(1/1) vm_util.py:420 DEBUG    Ran azure vm show --json pkb-dd272e43-1. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-21 12:01:25,589 dd272e43 Thread-4 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:25,590 dd272e43 Thread-5 iperf(1/1) vm_util.py:420 DEBUG    Ran azure vm show --json pkb-dd272e43-0. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-21 12:01:25,590 dd272e43 Thread-5 iperf(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-21 12:01:25,590 dd272e43 Thread-4 iperf(1/1) vm_util.py:392 INFO     Running: azure service delete --quiet pkb-dd272e43-1
