2015-07-23 14:18:30,182 a198d706 MainThread pkb.py:336 INFO     Flag values:
--machine_type=Standard_D2
--cloud=Azure
--benchmarks=hadoop_terasort
2015-07-23 14:18:30,254 a198d706 MainThread publisher.py:501 DEBUG    Using publishers: [<LogPublisher logger=<logging.RootLogger object at 0x7f35c07d8990> level=20>, <PrettyPrintStreamPublisher stream=<open file '<stdout>', mode 'w' at 0x7f35c22d7150>>, <NewlineDelimitedJSONPublisher file_path="/tmp/perfkitbenchmarker/run_a198d706/perfkitbenchmarker_results.json" mode="wb">]
2015-07-23 14:18:30,254 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,255 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,255 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,255 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,256 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,256 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,256 a198d706 MainThread hadoop_terasort(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-23 14:18:30,257 a198d706 MainThread hadoop_terasort(1/1) pkb.py:194 INFO     Preparing benchmark hadoop_terasort
2015-07-23 14:18:30,263 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:30,264 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure account affinity-group create --location=East US --label=perfkita198d7067df00ba2b perfkita198d7067df00ba2b
2015-07-23 14:18:31,532 a198d706 Thread-3 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,532 a198d706 Thread-3 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-8
2015-07-23 14:18:31,534 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure account affinity-group create --location=East US --label=perfkita198d7067df00ba2b perfkita198d7067df00ba2b. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:31,535 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,535 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure account affinity-group show --json perfkita198d7067df00ba2b
2015-07-23 14:18:31,537 a198d706 Thread-4 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,537 a198d706 Thread-4 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-7
2015-07-23 14:18:31,549 a198d706 Thread-5 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,550 a198d706 Thread-5 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-6
2015-07-23 14:18:31,554 a198d706 Thread-9 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,556 a198d706 Thread-9 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-5
2015-07-23 14:18:31,562 a198d706 Thread-10 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,564 a198d706 Thread-10 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-4
2015-07-23 14:18:31,568 a198d706 Thread-12 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,569 a198d706 Thread-12 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-3
2015-07-23 14:18:31,577 a198d706 Thread-14 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,577 a198d706 Thread-14 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-2
2015-07-23 14:18:31,582 a198d706 Thread-16 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,582 a198d706 Thread-16 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-1
2015-07-23 14:18:31,586 a198d706 Thread-17 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:31,586 a198d706 Thread-17 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a198d706-0
2015-07-23 14:18:33,316 a198d706 MainThread hadoop_terasort(1/1) pkb.py:426 INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/run_a198d706/pkb.log
2015-07-23 14:18:33,323 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:420 DEBUG    Ran azure account affinity-group show --json perfkita198d7067df00ba2b. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,319 a198d706 Thread-4 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-7. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,327 a198d706 Thread-4 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:33,319 a198d706 Thread-9 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-5. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,321 a198d706 Thread-17 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-0. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,327 a198d706 Thread-9 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:33,327 a198d706 Thread-4 hadoop_terasort(1/1) vm_util.py:392 INFO     Running: azure vm show --json pkb-a198d706-7
2015-07-23 14:18:33,328 a198d706 Thread-17 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:33,323 a198d706 Thread-3 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-8. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,323 a198d706 Thread-1 hadoop_terasort(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureAffinityGroup failed.
2015-07-23 14:18:33,326 a198d706 Thread-10 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-4. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,330 a198d706 Thread-10 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:33,330 a198d706 Thread-3 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-23 14:18:33,326 a198d706 Thread-5 hadoop_terasort(1/1) vm_util.py:418 INFO     Ran azure vm delete --quiet pkb-a198d706-6. Got return code (-2).
STDOUT: 
STDERR: 
2015-07-23 14:18:33,332 a198d706 Thread-5 hadoop_terasort(1/1) vm_util.py:389 DEBUG    Environment variables: None
